# Generated by Django 4.2.7 on 2025-11-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
