# Generated by Django 4.2.7 on 2025-11-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=100)),
            ],
            options={
                'verbose_name': 'Daily Task',
                'verbose_name_plural': 'Daily Tasks',
            },
        ),
        migrations.CreateModel(
            name='deadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remind_me_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=100)),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
            },
        ),
        migrations.CreateModel(
            name='KindReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=100)),
            ],
            options={
                'verbose_name': 'Kind Reminder',
                'verbose_name_plural': 'Kind Reminders',
            },
        ),
        migrations.CreateModel(
            name='SpecialDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('datetime', models.DateField()),
            ],
            options={
                'verbose_name': 'Special Day',
                'verbose_name_plural': 'Special Days',
            },
        ),
    ]
