# Generated by Django 4.2.7 on 2025-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlines',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialdays',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for duration (when is_duration=True)', null=True),
        ),
        migrations.AddField(
            model_name='specialdays',
            name='is_duration',
            field=models.BooleanField(default=False, help_text='True for date range, False for single day'),
        ),
        migrations.AddField(
            model_name='specialdays',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for duration (when is_duration=True)', null=True),
        ),
        migrations.AlterField(
            model_name='specialdays',
            name='datetime',
            field=models.DateField(blank=True, help_text='Single day date (when is_duration=False)', null=True),
        ),
    ]
