# Generated by Django 4.2.7 on 2025-11-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_deadlines_name_specialdays_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadlines',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kindreminder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kind_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialdays',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_days', to=settings.AUTH_USER_MODEL),
        ),
    ]
